### ISSUE TITLE
demo-page-header installed, but the yellow bar will not turn to green

### ISSUE THREAD

**Issue by mubiesam** [Pancake-CMS/demo-page-header#1]
followed the setup procedure, but  the yellow bar will not turn to green

I used polymer serve to run on
http://127.0.0.1:8081/components/developer-console/#/components
will it be the problem?

Thanks

**Comment by prateekjadhwani** [comment]
You can change the path here for your components 
https://github.com/Pancake-CMS/component-item/blob/master/component-item.html#L84 
This will not only download the elements from the correct location, but will also update the status of downloaded components.

**Comment by mubiesam** [comment]
Thanks for your quick response.

2017年5月13日 下午10:56，"Prateek Jadhwani" <notifications@github.com>寫道：

**Comment by prateekjadhwani** [comment]
Sure, no worries :)
